# Generated by Django 3.2.7 on 2021-10-21 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0003_auto_20211021_1128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='income_category',
        ),
        migrations.AddField(
            model_name='expense',
            name='expense_category',
            field=models.ForeignKey(default=44, on_delete=django.db.models.deletion.SET_DEFAULT, to='expense.expensecategory'),
        ),
    ]
