# Generated by Django 3.2.7 on 2021-10-21 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0004_auto_20211021_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='entry_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
